export default defineEventHandler(async (event) => {
    return {
        statusId: 1,
        priorityId: 2,
        driverId: 101,
        warehouseAgentId: 50,
        assignedDoorId: 5,
        code: "ORD-2025-001",
        status: "In Progress",
        priority: "High",
        assignedDoor: "Door A",
        active: true,
        truckCompany: "ABC Logistics",
        totalAwbs: 3,
        totalWeight: 1500.5,
        isIacCcsf: true,
        iacCcsf: {
            sealPhotos: ["photo1.jpg", "photo2.jpg"],
            verificationNotes: "All seals verified",
            verified: true,
            report: true,
            endDate: new Date("2025-01-15"),
        },
        awbs: [
            {
                id: 1001,
                code: "002-8765-4321",
                statusId: 3,
                status: "Pending",
                natureOfGoods: "Electronics",
                totalNumberOfPieces: 10,
                totalWeight: 500.25,
                shc: [1, 2, 3],
                pendingDgCheck: false,
            }
        ],
        driver: {
            fullName: "John Doe",
            registrationDate: new Date("2024-06-01"),
            licensePhoto: "https://s7d9.scene7.com/is/image/statepa/real%20id-compliant%20non-commercial%20driver_s%20license%20-%20mid-renewal%20cycle",
        },
        smsId: 200,
        driverCheckIn: new Date("2025-01-10T08:00:00"),
        driverCheckOut: new Date("2025-01-10T17:00:00"),
        verifiedDriver: true,
        completed: false,
        completionDate: new Date("2025-01-15"),
        proofOfAcceptance: "signature.pdf",
        createdAt: new Date("2025-01-01"),
    }
})